# -*- coding: utf-8 -*-
"""Copy of EmailSpamClassifierStarter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3X40EWtfHl0MXvyKZgl2zMEaByjxCFa
"""

"""
Dataset: https://www.kaggle.com/venky73/spam-mails-dataset

Use the scikit-learn and nltk packages to build a Naive Bayes classifier that determines whether or not an email is spam.. Then run your classifier on some test data to determine its accuracy.
"""

import nltk
import pandas as pd
from nltk.corpus import stopwords


filepath = "https://static.junilearning.com/ai_level_2/emails.csv"

# Dataset: https://www.kaggle.com/venky73/spam-mails-dataset
# read in data and remove unnecessary columns
data = pd.read_csv(filepath)
data = data.drop('messageid', axis=1)
data = data.drop('label', axis=1)
data.drop_duplicates(inplace=True)
