# -*- coding: utf-8 -*-
"""Copy of Updated WeatherImageClassifer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1booRkfVc0L_CrVbKsO-nfTMrr5D_prNV
"""

"""
Dataset: https://data.mendeley.com/datasets/4drtyfjtfy/1

Use the given dataset and the keras package to build a neural network image classifier that categorizes an image as rainy, sunny, cloudy or sunrise.
"""

import os

from keras.layers import Activation, Conv2D, Dense, Dropout, Flatten, MaxPooling2D
from keras.models import Sequential
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import get_file


"""# New Section"""

imagegen = ImageDataGenerator(rescale=1. / 255., rotation_range=30, horizontal_flip=True, validation_split=0.1)

# path_to_zip = get_file('weatherData.zip', origin="https://static.junilearning.com/ai_level_2/weatherData.zip", extract=True)
path_to_zip = get_file('weatherData.zip', origin="https://static.classes.jacobdanderson.net/weatherData.zip", extract=True)
# PATH = os.path.join(os.path.dirname(path_to_zip), 'weatherData')
PATH = os.path.join(os.path.dirname(path_to_zip), 'weatherData_extracted/weatherData')
train_dir = os.path.join(PATH, 'train')
validation_dir = os.path.join(PATH, 'validation')
test_dir = os.path.join(PATH, 'test')

train_generator = imagegen.flow_from_directory(train_dir, class_mode="categorical", shuffle=True, batch_size=128, target_size=(224, 224))
validation_generator = imagegen.flow_from_directory(validation_dir, class_mode="categorical", shuffle=True, batch_size=128, target_size=(
	224, 224))
test_generator = imagegen.flow_from_directory(test_dir, class_mode="categorical", shuffle=False, batch_size=128, target_size=(224, 224))

# build a sequential model
# Building the model
model = Sequential()

# 3 convolutional layers
model.add(Conv2D(32, (3, 3), input_shape=(224, 224, 3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

# 2 hidden layers
model.add(Flatten())
model.add(Dense(128))
model.add(Activation("relu"))

model.add(Dense(128))
model.add(Activation("relu"))

# The output layer with 4 neurons (1 per class)
model.add(Dense(4))
model.add(Activation("softmax"))

# compile model
model.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])
# fit on data for 10 epochs
model.fit(train_generator, epochs=10, validation_data=validation_generator)

accuracy = model.evaluate(test_generator)[1]
print(accuracy)

examples_datagen = ImageDataGenerator(rescale=1. / 255)
examples_generator = examples_datagen.flow_from_directory(
	PATH,
	target_size=(224, 224),
	classes=['examples'],
	shuffle=False)
examples_generator.reset()
preds = model.predict(examples_generator)
predicted_classes = []
for pred in preds:
	predicted_class = -1
	max = -1
	for i in range(len(pred)):
		if pred[i] > max:
			max = pred[i]
			predicted_class = i
	predicted_classes.append(predicted_class)

for pred, name in zip(predicted_classes, examples_generator.filenames):
	print(f'Filename: {name}')
	print(f'Label: {list(train_generator.class_indices.items())[pred][0]}')
	print()
