# -*- coding: utf-8 -*-
"""Copy of Updated WeatherImageClassiferStarter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1daZ03k3RJg2EVVvUg1SI8NEw5taXm19j
"""

"""
Dataset: https://data.mendeley.com/datasets/4drtyfjtfy/1

Use the given dataset and the keras package to build a neural network image classifier that categorizes an image as rainy, sunny, cloudy or sunrise.
"""

import os

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import get_file


imagegen = ImageDataGenerator(rescale=1. / 255., rotation_range=30, horizontal_flip=True, validation_split=0.1)

# path_to_zip = get_file('weatherData.zip', origin="https://static.junilearning.com/ai_level_2/weatherData.zip", extract=True)
path_to_zip = get_file('weatherData.zip', origin="https://static.classes.jacobdanderson.net/weatherData.zip", extract=True)
PATH = os.path.join(os.path.dirname(path_to_zip), 'weatherData_extracted/weatherData')
train_dir = os.path.join(PATH, 'train')
validation_dir = os.path.join(PATH, 'validation')
test_dir = os.path.join(PATH, 'test')

train_generator = imagegen.flow_from_directory(train_dir, class_mode="categorical", shuffle=True, batch_size=128, target_size=(224, 224))
validation_generator = imagegen.flow_from_directory(validation_dir, class_mode="categorical", shuffle=True, batch_size=128, target_size=(
	224, 224))
test_generator = imagegen.flow_from_directory(test_dir, class_mode="categorical", shuffle=False, batch_size=128, target_size=(224, 224))
