# -*- coding: utf-8 -*-
"""NeuralNetworksHousePriceRegressionStarter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yuCcN855nKnL_25zYHiN8QORMhIy2zLm
"""

"""
Dataset: https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html

Use the keras package and neural networks to build a regression model that predicts the prices of houses based on the characteristics of the house and its neighborhood.
"""

from keras.datasets import boston_housing


# load dataset and split into training and testing data
# Dataset Info: https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html
(x_train, y_train), (x_test, y_test) = boston_housing.load_data()
