# -*- coding: utf-8 -*-
"""Copy of DiabetesNeuralNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSGCUiIqK7SosJSdE8Hm4kdPa-13phuG
"""

"""
Dataset: https://www.kaggle.com/uciml/pima-indians-diabetes-database

Use packages like keras, scikit-learn and tensorflow to build a neural network classifier that predicts whether or not a patient has diabetes.
"""

import pandas as pd
from keras.layers import Dense
from keras.models import Sequential
from sklearn.model_selection import train_test_split


"""# New Section"""

# read in data and split into feature vectors and classifications
# filepath = 'https://static.junilearning.com/ai_level_2/diabetes.csv'
filepath = 'https://static.classes.jacobdanderson.net/diabetes.csv'
# dataset: https://www.kaggle.com/uciml/pima-indians-diabetes-database
data = pd.read_csv(filepath)
X = data.drop("Outcome", axis=1)
y = data["Outcome"]

# X.head()
# y.head()

# split into testing and training data
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# build a sequential neural net
# first layer takes in a vector of size 8 (the feature vector size), has 20 nodes and activation function relu
# second layer has 12 nodes and activation function relu
# third layer has 1 node and uses the sigmoid activation function
model = Sequential()
model.add(Dense(20, input_dim=8, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=300, validation_split=0.2, batch_size=10)

# run on testing data and get accuracy
print(model.evaluate(x_test, y_test)[1])

# see predictions of the testing data
predictions = (model.predict(x_test) > 0.5).astype("int32")
print(predictions)
