# -*- coding: utf-8 -*-
"""Copy of DiabetesNeuralNetStarter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hIoerxeF8AgFqAz68zRy1gtndav-nu6
"""

"""
Dataset: https://www.kaggle.com/uciml/pima-indians-diabetes-database

Use packages like keras, scikit-learn and tensorflow to build a neural network classifier that predicts whether or not a patient has diabetes.
"""

import pandas as pd


# filepath = 'https://static.junilearning.com/ai_level_2/diabetes.csv'
filepath = 'https://static.classes.jacobdanderson.net/diabetes.csv'
# dataset: https://www.kaggle.com/uciml/pima-indians-diabetes-database
# read in data and split into feature vectors and classifications
data = pd.read_csv(filepath)
X = data.drop("Outcome", axis=1)
y = data["Outcome"]

# X.head()
# y.head()
